version: "3.9"

services:
  mailai:
    image: ghcr.io/<org>/rpi-mailai:latest
    platform: linux/arm64
    restart: unless-stopped
    environment:
      - LLM_MODEL_PATH=/models/model.gguf
      - LLM_N_THREADS=3
      - LLM_CTX_SIZE=2048
      - MAILAI_ACCOUNTS=/etc/mailai/accounts.yaml
      - MAILAI_LOG_LEVEL=INFO
      - MAILAI_IMAP_TIMEOUT=30
      - TZ=Europe/Paris
    volumes:
      - ./data:/var/lib/mailai:rw
      - ./config:/etc/mailai:ro
      - ./models:/models:ro
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "python", "-m", "mailai.health_llm"]
      interval: 30s
      timeout: 5s
      retries: 5
